# Generated by Django 5.2.2 on 2025-06-05 23:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiftEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift_type', models.CharField(choices=[('squat', 'Squat'), ('bench', 'Bench Press'), ('deadlift', 'Deadlift'), ('ohp', 'Overhead Press')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.FloatField(help_text='Weight lifted (lbs)')),
                ('reps', models.PositiveIntegerField()),
                ('rpe', models.FloatField(help_text='RPE (Rate of Perceived Exertion), typically 1–10')),
                ('estimated_1rm', models.FloatField(editable=False)),
            ],
        ),
    ]
